version: '3'

services:
  web:
    build:
      context: .
    image: ${NESTJS_STARTER_IMAGE:-nestjs-starter:local}
    container_name: kufarm
    entrypoint: scripts/web-docker-entrypoint.sh
    command: yarn start:dev
    ports:
      - "3000:3000"
    volumes:
      - ${DUMMY_MOUNT:-.:/app}
